export interface evolutionVariable{
    idCentro: number,
    idVariable: number,
    numerico: number,
    idReporte: number,
    periodo_desde: Date,
    fecha_entrega: Date,
    periodo_hasta: Date,
    fecha_completado: Date,
    nombreVariable: string,
    fecha_creacion: Date,
    femenino: number,
    masculino: number,
    no_Binario: number,
}